//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomInfoRemote.Resx {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoomInfoRemote.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calendar ähnelt.
        /// </summary>
        internal static string CalendarPageTab_Title {
            get {
                return ResourceManager.GetString("CalendarPageTab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overview ähnelt.
        /// </summary>
        internal static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dim device ähnelt.
        /// </summary>
        internal static string RoomItem_Dim {
            get {
                return ResourceManager.GetString("RoomItem_Dim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string RoomPage_AddButton_Text {
            get {
                return ResourceManager.GetString("RoomPage_AddButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Day ähnelt.
        /// </summary>
        internal static string RoomPage_AllDayButton_Text {
            get {
                return ResourceManager.GetString("RoomPage_AllDayButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string RoomPage_CancelButton_Text {
            get {
                return ResourceManager.GetString("RoomPage_CancelButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string RoomPage_DeleteButton_Text {
            get {
                return ResourceManager.GetString("RoomPage_DeleteButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appointment description ähnelt.
        /// </summary>
        internal static string RoomPage_ReservationDescription_Placeholder {
            get {
                return ResourceManager.GetString("RoomPage_ReservationDescription_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appointment title ähnelt.
        /// </summary>
        internal static string RoomPage_ReservationTitle_Placeholder {
            get {
                return ResourceManager.GetString("RoomPage_ReservationTitle_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string RoomPage_SaveButton_Text {
            get {
                return ResourceManager.GetString("RoomPage_SaveButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ABSENT ähnelt.
        /// </summary>
        internal static string RoomsPage_Occupancy_Absent {
            get {
                return ResourceManager.GetString("RoomsPage_Occupancy_Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BUSY ähnelt.
        /// </summary>
        internal static string RoomsPage_Occupancy_Busy {
            get {
                return ResourceManager.GetString("RoomsPage_Occupancy_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FREE ähnelt.
        /// </summary>
        internal static string RoomsPage_Occupancy_Free {
            get {
                return ResourceManager.GetString("RoomsPage_Occupancy_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LOCKED ähnelt.
        /// </summary>
        internal static string RoomsPage_Occupancy_Locked {
            get {
                return ResourceManager.GetString("RoomsPage_Occupancy_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OCCUPIED ähnelt.
        /// </summary>
        internal static string RoomsPage_Occupancy_Occupied {
            get {
                return ResourceManager.GetString("RoomsPage_Occupancy_Occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PRESENT ähnelt.
        /// </summary>
        internal static string RoomsPage_Occupancy_Present {
            get {
                return ResourceManager.GetString("RoomsPage_Occupancy_Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extend by 15 minutes ähnelt.
        /// </summary>
        internal static string RoomsPage_ReservationExtensionButton_Text {
            get {
                return ResourceManager.GetString("RoomsPage_ReservationExtensionButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rooms ähnelt.
        /// </summary>
        internal static string RoomsTabTitle {
            get {
                return ResourceManager.GetString("RoomsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About this application ähnelt.
        /// </summary>
        internal static string SettingsPage_About {
            get {
                return ResourceManager.GetString("SettingsPage_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roominfo Remote -  ähnelt.
        /// </summary>
        internal static string SettingsPage_Application_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Made in Germany and developed by ähnelt.
        /// </summary>
        internal static string SettingsPage_Made_in_Germany {
            get {
                return ResourceManager.GetString("SettingsPage_Made_in_Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port selection ähnelt.
        /// </summary>
        internal static string SettingsPage_Ports {
            get {
                return ResourceManager.GetString("SettingsPage_Ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy Policy ähnelt.
        /// </summary>
        internal static string SettingsPage_Privacy_Policy {
            get {
                return ResourceManager.GetString("SettingsPage_Privacy_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://3lys1um.myqnapcloud.com/Datenschutz/roominfo/en/ ähnelt.
        /// </summary>
        internal static string SettingsPage_Privacy_Uri {
            get {
                return ResourceManager.GetString("SettingsPage_Privacy_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support ähnelt.
        /// </summary>
        internal static string SettingsPage_Support {
            get {
                return ResourceManager.GetString("SettingsPage_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TCP-Port: ähnelt.
        /// </summary>
        internal static string SettingsPage_TcpPort {
            get {
                return ResourceManager.GetString("SettingsPage_TcpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        internal static string SettingsPage_Theme_Dark {
            get {
                return ResourceManager.GetString("SettingsPage_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        internal static string SettingsPage_Theme_Default {
            get {
                return ResourceManager.GetString("SettingsPage_Theme_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        internal static string SettingsPage_Theme_Light {
            get {
                return ResourceManager.GetString("SettingsPage_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme selection ähnelt.
        /// </summary>
        internal static string SettingsPage_Themes {
            get {
                return ResourceManager.GetString("SettingsPage_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UDP-Port: ähnelt.
        /// </summary>
        internal static string SettingsPage_UdpPort {
            get {
                return ResourceManager.GetString("SettingsPage_UdpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string SettingsTabTitle {
            get {
                return ResourceManager.GetString("SettingsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standardweek ähnelt.
        /// </summary>
        internal static string StandardWeekPageTab_Title {
            get {
                return ResourceManager.GetString("StandardWeekPageTab_Title", resourceCulture);
            }
        }
    }
}
